name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "khushnoodasif/action-hashnode-blog@main"
        with:
          USERNAME: 'khushnoodasif'
          COUNT: 10
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
